# Generated by Django 3.1.5 on 2021-05-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('fulltname', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=6)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('participant', models.CharField(choices=[('Participant', 'Participant'), ('Speaker', 'Speaker')], default='Participant', max_length=150)),
                ('topic_to_Present', models.CharField(max_length=250)),
            ],
        ),
    ]
